# Generated by Django 3.1.7 on 2021-04-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Graduate', 'Graduate')], max_length=50, null=True)),
                ('first_name', models.CharField(max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120, null=True)),
                ('father_name', models.CharField(max_length=120, null=True)),
                ('home_number', models.CharField(max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=120, null=True)),
                ('job', models.CharField(max_length=120, null=True)),
                ('address', models.CharField(max_length=120, null=True)),
                ('bdate', models.DateField(null=True)),
                ('level_id', models.CharField(choices=[('مبتدئ أ', 'مبتدئ أ'), ('مبتدئ ب', 'مبتدئ ب'), ('متوسط أ', 'متوسط أ'), ('متوسط ب', 'متوسط ب'), ('متقدم أ', 'متقدم أ'), ('متقدم ب', 'متقدم ب')], max_length=50, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField()),
                ('level_id', models.CharField(choices=[('مبتدئ أ', 'مبتدئ أ'), ('مبتدئ ب', 'مبتدئ ب'), ('متوسط أ', 'متوسط أ'), ('متوسط ب', 'متوسط ب'), ('متقدم أ', 'متقدم أ'), ('متقدم ب', 'متقدم ب')], max_length=50, null=True)),
                ('position_id', models.CharField(choices=[('حرم رئيسي', 'حرم رئيسي'), ('توسعة حرم رئيسي', 'توسعة حرم رئيسي'), ('تحت السدة', 'تحت السدة'), ('توسعة مكتبة', 'توسعة مكتبة'), ('قبو', 'قبو')], max_length=50, null=True)),
                ('time_id', models.CharField(choices=[('بعد جلسة الصفا', 'بعد جلسة الصفا')], max_length=50, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.course')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almaher.person')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.FloatField(null=True)),
                ('theoretical_mark', models.FloatField(null=True)),
                ('practical_mark', models.FloatField(null=True)),
                ('result', models.CharField(choices=[('إعادة', 'إعادة'), ('ناجح', 'ناجح'), ('نجاح شرطي', 'نجاح شرطي')], max_length=50, null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[('نظري', 'نظري'), ('عملي', 'عملي')], max_length=50, null=True)),
                ('time_id', models.CharField(choices=[('الامتحان الأول', 'الامتحان الأول'), ('التكميلي', 'التكميلي'), ('الاعادة', 'الاعادة')], max_length=50, null=True)),
                ('mark', models.FloatField(null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='almaher.person')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id', to='almaher.person')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('status', models.BooleanField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
            ],
        ),
    ]
