# Generated by Django 3.1.7 on 2021-03-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Type',
            fields=[
                ('per_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('home_number', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('job', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('bdate', models.DateField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person_type')),
            ],
        ),
    ]
