# Generated by Django 3.1.7 on 2021-05-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Graduate', 'Graduate')], max_length=50, null=True)),
                ('first_name', models.CharField(max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120, null=True)),
                ('father_name', models.CharField(max_length=120, null=True)),
                ('home_number', models.CharField(max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=120, null=True)),
                ('job', models.CharField(max_length=120, null=True)),
                ('address', models.CharField(max_length=120, null=True)),
                ('bdate', models.DateField(null=True)),
                ('priority_id', models.CharField(choices=[('مستمر', 'مستمر'), ('غير معروف', 'غير معروف')], max_length=50, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.level')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.course')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.level')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.position')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almaher.person')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session_Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='time_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.time'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attendance', models.FloatField(null=True)),
                ('theoretical_mark', models.FloatField(null=True)),
                ('practical_mark', models.FloatField(null=True)),
                ('result', models.CharField(choices=[('إعادة', 'إعادة'), ('ناجح', 'ناجح'), ('نجاح شرطي', 'نجاح شرطي')], max_length=50, null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[('نظري', 'نظري'), ('عملي', 'عملي')], max_length=50, null=True)),
                ('time_id', models.CharField(choices=[('الامتحان الأول', 'الامتحان الأول'), ('التكميلي', 'التكميلي'), ('الاعادة', 'الاعادة')], max_length=50, null=True)),
                ('mark', models.FloatField(null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='almaher.person')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id', to='almaher.person')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('status', models.BooleanField()),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
            ],
        ),
    ]
