# Generated by Django 3.1.7 on 2021-03-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.course')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.level')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.position')),
                ('student_id', models.ManyToManyField(related_name='student_id', to='almaher.Person')),
                ('teacher_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_id', to='almaher.person')),
                ('time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.time')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.level'),
        ),
    ]
