# Generated by Django 3.1.7 on 2021-04-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='course',
            new_name='course_id',
        ),
    ]
