# Generated by Django 3.1.7 on 2021-04-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.position'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.time'),
        ),
    ]
