# Generated by Django 3.1.7 on 2021-03-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_number', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.course')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.level')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.position')),
                ('student_id', models.ManyToManyField(to='almaher.Person')),
                ('time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.time')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('status', models.BooleanField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.class')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.person')),
            ],
        ),
    ]
