# Generated by Django 3.1.7 on 2021-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0002_auto_20210427_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='priority_id',
            field=models.CharField(choices=[('مستمر', 'مستمر'), ('غير معروف', 'غير معروف')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session_student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
