# Generated by Django 3.1.7 on 2021-04-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0002_auto_20210416_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(unique=True),
        ),
    ]
