# Generated by Django 3.1.7 on 2021-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0002_auto_20210504_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_of_session',
            field=models.IntegerField(null=True),
        ),
    ]
