# Generated by Django 3.1.7 on 2021-03-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0002_auto_20210328_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='student_id',
        ),
    ]
