# Generated by Django 3.1.7 on 2021-03-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0003_auto_20210327_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_id', to='almaher.person'),
        ),
        migrations.AlterField(
            model_name='class',
            name='student_id',
            field=models.ManyToManyField(related_name='student_id', to='almaher.Person'),
        ),
    ]
