# Generated by Django 3.1.7 on 2021-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0003_auto_20210416_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_time',
            name='exam_time_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam_type',
            name='exam_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person_type',
            name='per_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
