# Generated by Django 3.1.7 on 2021-04-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0003_remove_attendance_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.session'),
        ),
    ]
