# Generated by Django 3.1.7 on 2021-04-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0004_auto_20210416_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_type',
            name='per_type_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
