# Generated by Django 3.1.7 on 2021-03-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0004_session_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='create_date',
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almaher.person'),
        ),
    ]
