# Generated by Django 3.1.7 on 2021-03-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0004_auto_20210327_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.level'),
        ),
    ]
