# Generated by Django 3.1.7 on 2021-05-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0004_auto_20210514_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teacher_id',
        ),
    ]
