# Generated by Django 3.1.7 on 2021-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0005_auto_20210416_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
