# Generated by Django 3.1.7 on 2021-04-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0005_auto_20210409_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='session',
            new_name='session_id',
        ),
    ]
