# Generated by Django 3.1.7 on 2021-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0005_remove_exam_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(choices=[('ناجح', 'ناجح'), ('نجاح شرطي', 'نجاح شرطي'), ('إعادة', 'إعادة')], max_length=50, null=True),
        ),
    ]
