# Generated by Django 3.1.7 on 2021-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0006_auto_20210516_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('ناجح', 'ناجح'), ('نجاح شرطي', 'نجاح شرطي'), ('إعادة', 'إعادة')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='practical_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='theoretical_mark',
            field=models.IntegerField(null=True),
        ),
    ]
