# Generated by Django 3.1.7 on 2021-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0006_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(),
        ),
    ]
