# Generated by Django 3.1.7 on 2021-05-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0007_auto_20210516_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.person'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.session'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.session'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.level'),
        ),
        migrations.AlterField(
            model_name='result',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.session'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.person'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.course'),
        ),
        migrations.AlterField(
            model_name='session',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.level'),
        ),
        migrations.AlterField(
            model_name='session',
            name='position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.position'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.time'),
        ),
        migrations.AlterField(
            model_name='session_student',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.session'),
        ),
        migrations.AlterField(
            model_name='session_student',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.person'),
        ),
    ]
