# Generated by Django 3.1.7 on 2021-04-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0007_auto_20210420_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almaher.person_type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
