# Generated by Django 3.1.7 on 2021-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0008_auto_20210423_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
