# Generated by Django 3.1.7 on 2021-04-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0009_auto_20210423_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
