# Generated by Django 3.1.7 on 2021-04-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0010_auto_20210424_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='level_id',
            field=models.CharField(choices=[('مبتدأ أ', 'مبتدأ أ'), ('مبتدأ ب', 'مبتدأ ب')], max_length=50, null=True),
        ),
    ]
