# Generated by Django 3.1.7 on 2021-04-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0011_auto_20210424_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_type_id',
        ),
    ]
