# Generated by Django 3.1.7 on 2021-04-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0012_remove_person_person_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='type_id',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Graduate', 'Graduate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='level_id',
            field=models.CharField(choices=[('مبتدأ أ', 'مبتدأ أ'), ('مبتدأ ب', 'مبتدأ ب'), ('متوسط أ', 'متوسط أ'), ('متوسط ب', 'متوسط ب'), ('متقدم أ', 'متقدم أ'), ('متقدم ب', 'متقدم ب')], max_length=50, null=True),
        ),
    ]
