# Generated by Django 3.1.7 on 2021-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0015_auto_20210424_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='level_id',
            field=models.CharField(choices=[('مبتدئ أ', 'مبتدئ أ'), ('مبتدئ ب', 'مبتدئ ب'), ('متوسط أ', 'متوسط أ'), ('متوسط ب', 'متوسط ب'), ('متقدم أ', 'متقدم أ'), ('متقدم ب', 'متقدم ب')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='level_id',
            field=models.CharField(choices=[('مبتدئ أ', 'مبتدئ أ'), ('مبتدئ ب', 'مبتدئ ب'), ('متوسط أ', 'متوسط أ'), ('متوسط ب', 'متوسط ب'), ('متقدم أ', 'متقدم أ'), ('متقدم ب', 'متقدم ب')], max_length=50, null=True),
        ),
    ]
