# Generated by Django 3.1.7 on 2021-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0016_auto_20210425_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
