# Generated by Django 3.1.7 on 2021-04-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0017_auto_20210425_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[('نظري', 'نظري'), ('عملي', 'عملي')], max_length=50, null=True)),
                ('time_id', models.CharField(choices=[('الامتحان الأول', 'الامتحان الأول'), ('التكميلي', 'التكميلي'), ('الاعادة', 'الاعادة')], max_length=50, null=True)),
                ('result', models.FloatField(null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almaher.session')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='almaher.person')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id', to='almaher.person')),
            ],
        ),
    ]
