# Generated by Django 3.1.7 on 2021-04-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almaher', '0018_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='result',
            new_name='mark',
        ),
    ]
